name = "DoubleEnded"
uuid = "1bc4e7c2-c1e1-11e9-03fe-315bbef43fde"
authors = ["johti <johti17@liu.se>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ImmutableList = "4a558cac-c1ed-11e9-20da-3584bcd8709a"
